spring:
  config:
    activate:
      on-profile: prod

# 运行模式:  prod-生产模式(使用真实接口)
api:
  # 定义所有 API 类型的基地址映射
  urls:
    hisincome: "http://168.168.235.88:18401/orgine/powermsp/service/overt"
    hisoperator: "http://168.168.235.88:18401/orgine/powermsp/service/overt"
    holidaycalendar: "http://calendar-service.com/util"
    yqcashreg: "http://cash-reg-service.com/reports"