spring:
  application:
    name: auto-demo
server:
  port: 1888
browser:
  port: 9223

isOpenExportInterface: false #是否开启调用导出接口，默认false

yb:
  insutype: 310,390,515253,3101,3901
  insutype.cn: \u804c\u5de5\u57fa\u672c\u533b\u7597\u4fdd\u9669,\u57ce\u4e61\u5c45\u6c11\u57fa\u672c\u533b\u7597\u4fdd\u9669,\u751f\u80b2\u533b\u7597\u4fdd\u9669,\u5f02\u5730\u804c\u5de5\u57fa\u672c\u533b\u7597\u4fdd\u9669,\u5f02\u5730\u5c45\u6c11\u57fa\u672c\u533b\u7597\u4fdd\u9669
  bill:
    url: http://mas.cg.hsip.gov.cn/hds/back/web/gatherNetInfoEyDay/queryMedinsGatherNetInfoByDa
  token: 530137d4-9687-48b7-9b20-3cf10ecb3f18
  session: ZGY4MTYwODctNDg5NS00MjNlLThjYTEtZWQ2NTlmZjJlM2M0
  pageSize: 10000
  frontUrl: http://mas.cq.hsip.gov.cn/hds/N1703.html#/N170301?paggeKey=1
  fixmedinsCode: H50010606446
