# 应用基本配置
spring:
  application:
    name: medical-data-service
  profiles:
    active: mine  # 默认激活开发环境
  mvc:   # 确保 Spring Boot 在找不到 Handler 时抛出异常，而不是直接返回默认的 404 页面
    throw-exception-if-no-handler-found: true
  web:    # 确保 DispatcherServlet 对静态资源的处理不会影响到上面的配置
    resources:
      add-mappings: false
# 服务器配置
server:
  port: 8081
#
## --- Logback 相关的属性配置 ---
#logging:
#  # 日志文件存储路径 (请根据您的环境调整)
#  log-dir: logs
#
#  # 日志级别
#  level:
#    root: INFO
#    com.alibaba.druid: WARN
#    com.zaxxer.hikari: WARN
#    oracle.jdbc: WARN
#
#  # 控制台 Appender 的 Pattern (在 dev/test/default profile 下使用)
##  pattern:
##    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40c{1.}){cyan} %clr(:){faint} %m%n%wex"
##
##    # 文件 Appender 的 Pattern (在 prod profile 下使用)
##    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID} --- [%t] %-40.40c{1.} : %m%n%wex"
#
#  # 滚动策略相关的参数 (用于 logback-spring.xml)
#  max-file-size: 50MB           # 单个归档日志文件的最大大小
#  max-history-days: 30          # 最大历史文件保存天数


#请求头的配置
request:
  head:
    charset: UTF-8
    encryptType: AES
    enterpriseId: xinqiao
    language: zh_CN
    #方法需要动态
    method: orgine.powermsp.service.overt.extend.SP_GetHisIncome_938
    sign: 1
    signType: md5
    sysTrackCode: c92b2f334a7442b698b774e5ccc3e3f8
    #时间戳需要复制
    timestamp: 2023-10-01T12:00:00Z
    version: 1.0
    #accessToken可以不传
    accessToken: 123456
    #用的掌医小程序-管理门户
    appId: b16ff06f5fd44ab6b56e037d7ee1a6ed