# 应用基本配置
spring:
  application:
    name: medical-data-service
  profiles:
    active: prod  # 默认激活开发环境
  mvc:   # 确保 Spring Boot 在找不到 Handler 时抛出异常，而不是直接返回默认的 404 页面
    throw-exception-if-no-handler-found: true
  web:    # 确保 DispatcherServlet 对静态资源的处理不会影响到上面的配置
    resources:
      add-mappings: false

# 服务器配置
server:
  port: 18081


mybatis-plus:
  type-aliases-package: com.mergedata.domain
  mapper-locations: classpath*:mapper/**/*.xml # Ensure this is present if you use XML mappers

  configuration:
    jdbc-type-for-null: 'null' #全局配置允许mapper.xml写入null
    map-underscore-to-camel-case: true #开启下划线转驼峰
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #开启Db.save等方法查询具体的sql日志

  global-config:
    banner: false
    db-config:
      id-type: auto



logging:
  level:
    # 保持 MyBatis-Plus 的 INFO 或 DEBUG 级别（如果需要查看框架内部信息）
    com.baomidou.mybatisplus: info

    # 将您的 Mapper 接口所在包设置为 INFO
    # INFO 级别会打印 SQL 和参数，但不会打印 Row 数据
    com.mergedata.mapper: info

    # 确保 MyBatis 的执行器日志也设置为 INFO (如果仅设置 Mapper 包无效)
    org.apache.ibatis.executor: info

#    com.mergedata.util: info

  #  告诉 Spring Boot 使用自定义的 Logback 配置文件
  config: classpath:logback-spring.xml


app:
  log:
    # 1. 定义日志存储路径：项目根目录下的 /logs 文件夹
    dir: D:/logs/18081

    # 2. 定义单个文件的最大大小，达到此大小触发滚动
    max-file-size: 50MB

    # 3. 定义日志文件保留的最大天数 (maxHistory)
    max-history: 30

    #请求头的配置
request:
  head:
    charset: UTF-8
    encryptType: AES
    enterpriseId: xinqiao
    language: zh_CN
    #方法需要动态
#    method: orgine.powermsp.service.overt.extend.SP_GetHisIncome_938
    sign: 1
    signType: md5
    sysTrackCode: c92b2f334a7442b698b774e5ccc3e3f8
    #时间戳需要复制
    timestamp: 2023-10-01T12:00:00Z
    version: 1.0
    #accessToken可以不传
    accessToken: 123456
    #用的掌医小程序-管理门户
    appId: b16ff06f5fd44ab6b56e037d7ee1a6ed

# application.yml
springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    # 默认展开级别（设为-1可折叠所有Schemas）
    default-model-expand-depth: -1
    # 显示模型部分
    display-request-duration: true
    # 隐藏Schemas部分
    default-models-expand-depth: -1
    tags-sorter: alpha
    operations-sorter: alpha