# 激活开发环境配置
spring:
  config:
    activate:
      on-profile: dev

# 运行模式:  prod-生产模式(使用真实接口)
api:
  his: # HIS数据接口配置
    url: https://api.example.com/hisdata
  yq: # 预约挂号接口配置
    cash_url: https://api.example.com/yq
    operator_url: https://api.example.com/operator