spring:
  config:
    activate:
      on-profile: prod

# 运行模式:  prod-生产模式(使用真实接口)
api:
  his: # HIS数据接口配置
    url: https://api.example.com/hisdata
  yq: # 预约挂号接口配置
    url: https://api.example.com/yq